

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-tcp-tls
  labels:
    helm.sh/chart: atomic-blend-0.1.0
    app.kubernetes.io/name: atomic-blend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  secretName: backend-tcp-secret
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - example.com