
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-health
  annotations:
    haproxy.org/path-rewrite: /backend/(.*) /\1
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - api.example.com
      secretName: backend-tls
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /backend/health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80 