

---
apiVersion: ingress.v1.haproxy.org/v1
kind: TCP
metadata:
  name: backend-tcp
  labels:
    helm.sh/chart: atomic-blend-0.1.0
    app.kubernetes.io/name: atomic-blend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    ingress.class: haproxy
    haproxy.org/timeout-client: 30s
spec:
  - name: backend-tcp
    frontend:
      name: backend-frontend
      tcplog: true
      binds:
        - name: tcp-bind
          port: 8080
          accept_proxy: true
    service:
      name: backend
      port: 80