
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
  labels:
    helm.sh/chart: atomic-blend-0.1.0
    app.kubernetes.io/name: atomic-blend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    key1: encrypted_value1
    key2: encrypted_value2
  template:
    metadata:
      name: my-secret
      namespace: default
      labels:
        app: backend
    spec:
      type: Opaque