{{- range $serviceName, $serviceConfig := .Values.services }}
{{- $root := $ }}
{{ if or (or ($serviceConfig.serviceaccount).enabled ($serviceConfig.rbac).enabled) ($serviceConfig.rbac).enableAdminRbac }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}-sac
{{- end }}
{{- end }}